// <auto-generated />
using System;
using AutomotoraSaaS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomotoraSaaS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818071500_PreciosDeReferencia")]
    partial class PreciosDeReferencia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Busqueda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Filtros")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("filtros");

                    b.Property<int>("ResultadosCount")
                        .HasColumnType("int")
                        .HasColumnName("resultados_count");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("session_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_busquedas");

                    b.HasIndex("TenantId", "ResultadosCount", "CreatedAt")
                        .HasDatabaseName("ix_busquedas_tenant_id_resultados_count_created_at");

                    b.ToTable("busquedas", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("UsdUyu")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("usd_uyu");

                    b.HasKey("Id")
                        .HasName("pk_cotizaciones");

                    b.HasIndex("Fecha")
                        .IsUnique()
                        .HasDatabaseName("ix_cotizaciones_fecha");

                    b.ToTable("cotizaciones", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip_hash");

                    b.Property<string>("Metadata")
                        .HasColumnType("json")
                        .HasColumnName("metadata");

                    b.Property<string>("Referer")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("referer");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("session_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("user_agent");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_eventos");

                    b.HasIndex("VehiculoId")
                        .HasDatabaseName("ix_eventos_vehiculo_id");

                    b.HasIndex("TenantId", "VehiculoId", "Tipo", "CreatedAt")
                        .HasDatabaseName("ix_eventos_tenant_id_vehiculo_id_tipo_created_at");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_marcas");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_marcas_nombre");

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<int>("Carroceria")
                        .HasColumnType("int")
                        .HasColumnName("carroceria");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("marca_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_modelos");

                    b.HasIndex("MarcaId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_modelos_marca_id_nombre");

                    b.ToTable("modelos", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.PrecioReferencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("fuente");

                    b.Property<decimal>("Maximo")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("maximo");

                    b.Property<decimal>("Minimo")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("minimo");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int")
                        .HasColumnName("modelo_id");

                    b.Property<int>("Moneda")
                        .HasColumnType("int")
                        .HasColumnName("moneda");

                    b.Property<int>("Muestras")
                        .HasColumnType("int")
                        .HasColumnName("muestras");

                    b.Property<decimal>("Promedio")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("promedio");

                    b.HasKey("Id")
                        .HasName("pk_precios_referencia");

                    b.HasIndex("ModeloId", "Anio", "Fecha")
                        .HasDatabaseName("ix_precios_referencia_modelo_id_anio_fecha");

                    b.HasIndex("ModeloId", "Anio", "Moneda", "Fecha", "Fuente")
                        .IsUnique()
                        .HasDatabaseName("ix_precios_referencia_modelo_id_anio_moneda_fecha_fuente");

                    b.ToTable("precios_referencia", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expira_en");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revocado_en");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.SolicitudModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carroceria")
                        .HasColumnType("int")
                        .HasColumnName("carroceria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("marca_id");

                    b.Property<int?>("ModeloCreadoId")
                        .HasColumnType("int")
                        .HasColumnName("modelo_creado_id");

                    b.Property<string>("NombreModelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre_modelo");

                    b.Property<string>("NotaResolucion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("nota_resolucion");

                    b.Property<DateTime?>("ResueltaEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resuelta_en");

                    b.Property<int>("SolicitadaPorUserId")
                        .HasColumnType("int")
                        .HasColumnName("solicitada_por_user_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_solicitudes_modelo");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("ix_solicitudes_modelo_marca_id");

                    b.HasIndex("ModeloCreadoId")
                        .HasDatabaseName("ix_solicitudes_modelo_modelo_creado_id");

                    b.HasIndex("SolicitadaPorUserId")
                        .HasDatabaseName("ix_solicitudes_modelo_solicitada_por_user_id");

                    b.HasIndex("TenantId", "Estado")
                        .HasDatabaseName("ix_solicitudes_modelo_tenant_id_estado");

                    b.ToTable("solicitudes_modelo", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("ColorPrimario")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("color_primario");

                    b.Property<string>("ColorSecundario")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("color_secundario");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("DominioCustom")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dominio_custom");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("slug");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("DominioCustom")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_dominio_custom");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Rol")
                        .HasColumnType("int")
                        .HasColumnName("rol");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("color");

                    b.Property<int>("Combustible")
                        .HasColumnType("int")
                        .HasColumnName("combustible");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Destacado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("destacado");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_publicacion");

                    b.Property<DateTime?>("FechaVenta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_venta");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int")
                        .HasColumnName("kilometraje");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int")
                        .HasColumnName("modelo_id");

                    b.Property<int>("Moneda")
                        .HasColumnType("int")
                        .HasColumnName("moneda");

                    b.Property<string>("Motor")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("motor");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio");

                    b.Property<decimal?>("PrecioCosto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_costo");

                    b.Property<decimal?>("PrecioVenta")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_venta");

                    b.Property<int?>("Puertas")
                        .HasColumnType("int")
                        .HasColumnName("puertas");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Transmision")
                        .HasColumnType("int")
                        .HasColumnName("transmision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_vehiculos");

                    b.HasIndex("VersionId")
                        .HasDatabaseName("ix_vehiculos_version_id");

                    b.HasIndex("ModeloId", "Anio")
                        .HasDatabaseName("ix_vehiculos_modelo_id_anio");

                    b.HasIndex("TenantId", "Estado")
                        .HasDatabaseName("ix_vehiculos_tenant_id_estado");

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.VehiculoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPortada")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_portada");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url");

                    b.Property<string>("UrlThumb")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url_thumb");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_vehiculo_fotos");

                    b.HasIndex("VehiculoId", "Orden")
                        .HasDatabaseName("ix_vehiculo_fotos_vehiculo_id_orden");

                    b.ToTable("vehiculo_fotos", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.VersionVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int")
                        .HasColumnName("modelo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_versiones");

                    b.HasIndex("ModeloId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_versiones_modelo_id_nombre");

                    b.ToTable("versiones", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Busqueda", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_busquedas_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Evento", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_tenants_tenant_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_eventos_vehiculos_vehiculo_id");

                    b.Navigation("Tenant");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Modelo", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modelos_marcas_marca_id");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.PrecioReferencia", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_precios_referencia_modelos_modelo_id");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.SolicitudModelo", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solicitudes_modelo_marcas_marca_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Modelo", "ModeloCreado")
                        .WithMany()
                        .HasForeignKey("ModeloCreadoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_solicitudes_modelo_modelos_modelo_creado_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.User", "SolicitadaPor")
                        .WithMany()
                        .HasForeignKey("SolicitadaPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solicitudes_modelo_users_solicitada_por_user_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solicitudes_modelo_tenants_tenant_id");

                    b.Navigation("Marca");

                    b.Navigation("ModeloCreado");

                    b.Navigation("SolicitadaPor");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.User", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Vehiculo", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculos_modelos_modelo_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Vehiculos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculos_tenants_tenant_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.VersionVehiculo", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vehiculos_versiones_version_id");

                    b.Navigation("Modelo");

                    b.Navigation("Tenant");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.VehiculoFoto", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Fotos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculo_fotos_vehiculos_vehiculo_id");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.VersionVehiculo", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Modelo", "Modelo")
                        .WithMany("Versiones")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versiones_modelos_modelo_id");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Modelo", b =>
                {
                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Vehiculo", b =>
                {
                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
