// <auto-generated />
using System;
using AutomotoraSaaS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomotoraSaaS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.AvisoDeCobro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Destinatarios")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("destinatarios");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("PagaHasta")
                        .HasColumnType("date")
                        .HasColumnName("paga_hasta");

                    b.Property<int>("SuscripcionId")
                        .HasColumnType("int")
                        .HasColumnName("suscripcion_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_avisos_de_cobro");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_avisos_de_cobro_tenant_id");

                    b.HasIndex("SuscripcionId", "PagaHasta", "Estado")
                        .IsUnique()
                        .HasDatabaseName("ix_avisos_de_cobro_suscripcion_id_paga_hasta_estado");

                    b.ToTable("avisos_de_cobro", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Busqueda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Filtros")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("filtros");

                    b.Property<int>("ResultadosCount")
                        .HasColumnType("int")
                        .HasColumnName("resultados_count");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("session_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_busquedas");

                    b.HasIndex("TenantId", "ResultadosCount", "CreatedAt")
                        .HasDatabaseName("ix_busquedas_tenant_id_resultados_count_created_at");

                    b.ToTable("busquedas", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("UsdUyu")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("usd_uyu");

                    b.HasKey("Id")
                        .HasName("pk_cotizaciones");

                    b.HasIndex("Fecha")
                        .IsUnique()
                        .HasDatabaseName("ix_cotizaciones_fecha");

                    b.ToTable("cotizaciones", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Evento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ip_hash");

                    b.Property<string>("Metadata")
                        .HasColumnType("json")
                        .HasColumnName("metadata");

                    b.Property<string>("Referer")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("referer");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("session_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("user_agent");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_eventos");

                    b.HasIndex("VehiculoId")
                        .HasDatabaseName("ix_eventos_vehiculo_id");

                    b.HasIndex("TenantId", "VehiculoId", "Tipo", "CreatedAt")
                        .HasDatabaseName("ix_eventos_tenant_id_vehiculo_id_tipo_created_at");

                    b.ToTable("eventos", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_marcas");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_marcas_nombre");

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<int>("Carroceria")
                        .HasColumnType("int")
                        .HasColumnName("carroceria");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("marca_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_modelos");

                    b.HasIndex("MarcaId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_modelos_marca_id_nombre");

                    b.ToTable("modelos", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comprobante")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("comprobante");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Medio")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("medio");

                    b.Property<int>("Moneda")
                        .HasColumnType("int")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Nota")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("nota");

                    b.Property<DateOnly>("PeriodoDesde")
                        .HasColumnType("date")
                        .HasColumnName("periodo_desde");

                    b.Property<DateOnly>("PeriodoHasta")
                        .HasColumnType("date")
                        .HasColumnName("periodo_hasta");

                    b.Property<int>("SuscripcionId")
                        .HasColumnType("int")
                        .HasColumnName("suscripcion_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pagos");

                    b.HasIndex("SuscripcionId")
                        .HasDatabaseName("ix_pagos_suscripcion_id");

                    b.HasIndex("TenantId", "Fecha")
                        .HasDatabaseName("ix_pagos_tenant_id_fecha");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("HorasSoporteMes")
                        .HasColumnType("int")
                        .HasColumnName("horas_soporte_mes");

                    b.Property<bool>("IncluyeBenchmark")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("incluye_benchmark");

                    b.Property<bool>("IncluyeDominioPropio")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("incluye_dominio_propio");

                    b.Property<bool>("IncluyeReportes")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("incluye_reportes");

                    b.Property<int?>("MaxUsuarios")
                        .HasColumnType("int")
                        .HasColumnName("max_usuarios");

                    b.Property<int?>("MaxVehiculos")
                        .HasColumnType("int")
                        .HasColumnName("max_vehiculos");

                    b.Property<int>("Moneda")
                        .HasColumnType("int")
                        .HasColumnName("moneda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioMensual")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_mensual");

                    b.HasKey("Id")
                        .HasName("pk_planes");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_planes_codigo");

                    b.ToTable("planes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "vidriera",
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorasSoporteMes = 0,
                            IncluyeBenchmark = false,
                            IncluyeDominioPropio = false,
                            IncluyeReportes = false,
                            MaxUsuarios = 2,
                            MaxVehiculos = 40,
                            Moneda = 2,
                            Nombre = "Vidriera",
                            PrecioMensual = 4000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "demanda",
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorasSoporteMes = 2,
                            IncluyeBenchmark = false,
                            IncluyeDominioPropio = true,
                            IncluyeReportes = true,
                            MaxUsuarios = 6,
                            MaxVehiculos = 120,
                            Moneda = 2,
                            Nombre = "Demanda",
                            PrecioMensual = 6900m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "full",
                            CreatedAt = new DateTime(2026, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            HorasSoporteMes = 5,
                            IncluyeBenchmark = true,
                            IncluyeDominioPropio = true,
                            IncluyeReportes = true,
                            Moneda = 2,
                            Nombre = "Full",
                            PrecioMensual = 9900m
                        });
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.PrecioDeMercado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("fuente");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int")
                        .HasColumnName("modelo_id");

                    b.Property<int>("Moneda")
                        .HasColumnType("int")
                        .HasColumnName("moneda");

                    b.Property<decimal>("PrecioMaximo")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_maximo");

                    b.Property<decimal>("PrecioMediano")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_mediano");

                    b.Property<decimal>("PrecioMinimo")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_minimo");

                    b.Property<int>("Publicaciones")
                        .HasColumnType("int")
                        .HasColumnName("publicaciones");

                    b.HasKey("Id")
                        .HasName("pk_precios_de_mercado");

                    b.HasIndex("ModeloId", "Anio", "Fecha")
                        .HasDatabaseName("ix_precios_de_mercado_modelo_id_anio_fecha");

                    b.HasIndex("Fuente", "ModeloId", "Anio", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("ix_precios_de_mercado_fuente_modelo_id_anio_fecha");

                    b.ToTable("precios_de_mercado", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expira_en");

                    b.Property<DateTime?>("RevocadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revocado_en");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.SolicitudModelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Carroceria")
                        .HasColumnType("int")
                        .HasColumnName("carroceria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int")
                        .HasColumnName("marca_id");

                    b.Property<int?>("ModeloCreadoId")
                        .HasColumnType("int")
                        .HasColumnName("modelo_creado_id");

                    b.Property<string>("NombreModelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre_modelo");

                    b.Property<string>("NotaResolucion")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("nota_resolucion");

                    b.Property<DateTime?>("ResueltaEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resuelta_en");

                    b.Property<int>("SolicitadaPorUserId")
                        .HasColumnType("int")
                        .HasColumnName("solicitada_por_user_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_solicitudes_modelo");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("ix_solicitudes_modelo_marca_id");

                    b.HasIndex("ModeloCreadoId")
                        .HasDatabaseName("ix_solicitudes_modelo_modelo_creado_id");

                    b.HasIndex("SolicitadaPorUserId")
                        .HasDatabaseName("ix_solicitudes_modelo_solicitada_por_user_id");

                    b.HasIndex("TenantId", "Estado")
                        .HasDatabaseName("ix_solicitudes_modelo_tenant_id_estado");

                    b.ToTable("solicitudes_modelo", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Suscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Fin")
                        .HasColumnType("date")
                        .HasColumnName("fin");

                    b.Property<DateOnly>("Inicio")
                        .HasColumnType("date")
                        .HasColumnName("inicio");

                    b.Property<string>("MotivoDeBaja")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("motivo_de_baja");

                    b.Property<DateOnly>("PagaHasta")
                        .HasColumnType("date")
                        .HasColumnName("paga_hasta");

                    b.Property<int>("PlanId")
                        .HasColumnType("int")
                        .HasColumnName("plan_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TenantIdVigente")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("tenant_id_vigente")
                        .HasComputedColumnSql("CASE WHEN fin IS NULL THEN tenant_id END", true);

                    b.HasKey("Id")
                        .HasName("pk_suscripciones");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_suscripciones_plan_id");

                    b.HasIndex("TenantIdVigente")
                        .IsUnique()
                        .HasDatabaseName("ix_suscripciones_tenant_id_vigente");

                    b.HasIndex("TenantId", "Inicio")
                        .HasDatabaseName("ix_suscripciones_tenant_id_inicio");

                    b.ToTable("suscripciones", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("ColorPrimario")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("color_primario");

                    b.Property<string>("ColorSecundario")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("color_secundario");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("DominioCustom")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("dominio_custom");

                    b.Property<DateTime?>("DominioVerificadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dominio_verificado_en");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("slug");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("DominioCustom")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_dominio_custom");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("debe_cambiar_password");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Rol")
                        .HasColumnType("int")
                        .HasColumnName("rol");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("color");

                    b.Property<int>("Combustible")
                        .HasColumnType("int")
                        .HasColumnName("combustible");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Destacado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("destacado");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_publicacion");

                    b.Property<DateTime?>("FechaVenta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_venta");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int")
                        .HasColumnName("kilometraje");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int")
                        .HasColumnName("modelo_id");

                    b.Property<int>("Moneda")
                        .HasColumnType("int")
                        .HasColumnName("moneda");

                    b.Property<string>("Motor")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("motor");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio");

                    b.Property<decimal?>("PrecioCosto")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_costo");

                    b.Property<decimal?>("PrecioVenta")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("precio_venta");

                    b.Property<int?>("Puertas")
                        .HasColumnType("int")
                        .HasColumnName("puertas");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Transmision")
                        .HasColumnType("int")
                        .HasColumnName("transmision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int")
                        .HasColumnName("version_id");

                    b.HasKey("Id")
                        .HasName("pk_vehiculos");

                    b.HasIndex("VersionId")
                        .HasDatabaseName("ix_vehiculos_version_id");

                    b.HasIndex("ModeloId", "Anio")
                        .HasDatabaseName("ix_vehiculos_modelo_id_anio");

                    b.HasIndex("TenantId", "Estado")
                        .HasDatabaseName("ix_vehiculos_tenant_id_estado");

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.VehiculoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPortada")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("es_portada");

                    b.Property<int>("Orden")
                        .HasColumnType("int")
                        .HasColumnName("orden");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url");

                    b.Property<string>("UrlThumb")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("url_thumb");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_vehiculo_fotos");

                    b.HasIndex("VehiculoId", "Orden")
                        .HasDatabaseName("ix_vehiculo_fotos_vehiculo_id_orden");

                    b.ToTable("vehiculo_fotos", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.VersionVehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int")
                        .HasColumnName("modelo_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_versiones");

                    b.HasIndex("ModeloId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_versiones_modelo_id_nombre");

                    b.ToTable("versiones", (string)null);
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.AvisoDeCobro", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Suscripcion", "Suscripcion")
                        .WithMany()
                        .HasForeignKey("SuscripcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avisos_de_cobro_suscripciones_suscripcion_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avisos_de_cobro_tenants_tenant_id");

                    b.Navigation("Suscripcion");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Busqueda", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_busquedas_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Evento", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eventos_tenants_tenant_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_eventos_vehiculos_vehiculo_id");

                    b.Navigation("Tenant");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Modelo", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_modelos_marcas_marca_id");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Pago", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Suscripcion", "Suscripcion")
                        .WithMany("Pagos")
                        .HasForeignKey("SuscripcionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_suscripciones_suscripcion_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_tenants_tenant_id");

                    b.Navigation("Suscripcion");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.PrecioDeMercado", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_precios_de_mercado_modelos_modelo_id");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.SolicitudModelo", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solicitudes_modelo_marcas_marca_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Modelo", "ModeloCreado")
                        .WithMany()
                        .HasForeignKey("ModeloCreadoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_solicitudes_modelo_modelos_modelo_creado_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.User", "SolicitadaPor")
                        .WithMany()
                        .HasForeignKey("SolicitadaPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_solicitudes_modelo_users_solicitada_por_user_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_solicitudes_modelo_tenants_tenant_id");

                    b.Navigation("Marca");

                    b.Navigation("ModeloCreado");

                    b.Navigation("SolicitadaPor");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Suscripcion", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripciones_planes_plan_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suscripciones_tenants_tenant_id");

                    b.Navigation("Plan");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.User", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Vehiculo", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculos_modelos_modelo_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.Tenant", "Tenant")
                        .WithMany("Vehiculos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculos_tenants_tenant_id");

                    b.HasOne("AutomotoraSaaS.Core.Entities.VersionVehiculo", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_vehiculos_versiones_version_id");

                    b.Navigation("Modelo");

                    b.Navigation("Tenant");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.VehiculoFoto", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Vehiculo", "Vehiculo")
                        .WithMany("Fotos")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehiculo_fotos_vehiculos_vehiculo_id");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.VersionVehiculo", b =>
                {
                    b.HasOne("AutomotoraSaaS.Core.Entities.Modelo", "Modelo")
                        .WithMany("Versiones")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versiones_modelos_modelo_id");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Modelo", b =>
                {
                    b.Navigation("Versiones");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Suscripcion", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("AutomotoraSaaS.Core.Entities.Vehiculo", b =>
                {
                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
